"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { auth, db } from "@/firebase/config";
import {
  collection,
  addDoc,
  onSnapshot,
  query,
  orderBy,
} from "firebase/firestore";
import { Expense } from "@/types/expense";
import {
  PlusIcon,
  CurrencyDollarIcon,
  UserCircleIcon,
  TagIcon,
  ArrowLeftIcon,
  ArrowDownTrayIcon,
  ArrowRightOnRectangleIcon,
} from "@heroicons/react/24/solid";

// PDF Libraries
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function DashboardPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [crops, setCrops] = useState<{ id: string; name: string }[]>([]);
  const [user, setUser] = useState<any>(null);

  // Modals & Selection
  const [showExpenseModal, setShowExpenseModal] = useState(false);
  const [showCropModal, setShowCropModal] = useState(false);
  const [selectedCropId, setSelectedCropId] = useState<string | null>(null);

  // Form States
  const [amount, setAmount] = useState("");
  const [desc, setDesc] = useState("");
  const [newCropName, setNewCropName] = useState("");

  useEffect(() => {
    const unsubscribeAuth = onAuthStateChanged(auth, (u) => {
      if (u) setUser(u);
      else window.location.href = "/login";
    });

    // Listen to Crops
    const unsubCrops = onSnapshot(collection(db, "crops"), (snap) => {
      setCrops(snap.docs.map((doc) => ({ id: doc.id, name: doc.data().name })));
    });

    // Listen to All Expenses
    const unsubExp = onSnapshot(collection(db, "expenses"), (snap) => {
      setExpenses(
        snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })) as Expense[],
      );
    });

    return () => {
      unsubscribeAuth();
      unsubCrops();
      unsubExp();
    };
  }, []);

  // --- PDF EXPORT LOGIC ---
  const exportToPDF = () => {
    const doc = new jsPDF();
    const dateStr = new Date().toLocaleDateString();
    const activeCropName =
      crops.find((c) => c.id === selectedCropId)?.name || "Crop";

    doc.setFontSize(20);
    doc.text(`${activeCropName} - Expense Report`, 14, 20);
    doc.setFontSize(10);
    doc.text(`Report Date: ${dateStr}`, 14, 28);
    doc.text(`Generated by: ${user?.displayName || user?.email}`, 14, 34);

    // Summary Table
    autoTable(doc, {
      startY: 40,
      head: [["Summary", "Total PKR"]],
      body: [
        ["Overall Total", total.toLocaleString()],
        ["Dr Shahzad Contribution", shahzadTotal.toLocaleString()],
        ["Azhar Contribution", azharTotal.toLocaleString()],
      ],
      theme: "striped",
      headStyles: { fillColor: [22, 163, 74] }, // Green
    });

    // Detailed List
    const tableData = filteredExpenses.map((e) => [
      new Date(e.date).toLocaleDateString(),
      e.description,
      e.addedBy,
      e.amount.toLocaleString(),
    ]);

    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [["Date", "Description", "Paid By", "Amount"]],
      body: tableData,
    });

    doc.save(`${activeCropName}_Expenses.pdf`);
  };

  const handleAddCrop = async () => {
    if (!newCropName) return;
    await addDoc(collection(db, "crops"), {
      name: newCropName,
      createdAt: new Date().toISOString(),
    });
    setNewCropName("");
    setShowCropModal(false);
  };

  const handleAddExpense = async () => {
    if (!user || !amount || !desc || !selectedCropId) return;
    const addedBy = user.email?.toLowerCase().includes("azhar")
      ? "Azhar"
      : "Dr Shahzad";

    await addDoc(collection(db, "expenses"), {
      amount: parseFloat(amount),
      description: desc,
      cropId: selectedCropId,
      addedBy,
      date: new Date().toISOString(),
    });

    setShowExpenseModal(false);
    setAmount("");
    setDesc("");
  };

  // Calculations
  const activeCrop = crops.find((c) => c.id === selectedCropId);
  const filteredExpenses = expenses.filter(
    (e) => (e as any).cropId === selectedCropId,
  );
  const total = filteredExpenses.reduce((sum, e) => sum + e.amount, 0);
  const azharTotal = filteredExpenses
    .filter((e) => e.addedBy === "Azhar")
    .reduce((sum, e) => sum + e.amount, 0);
  const shahzadTotal = filteredExpenses
    .filter((e) => e.addedBy === "Dr Shahzad")
    .reduce((sum, e) => sum + e.amount, 0);

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header with User Info */}
      <header className="bg-white border-b px-6 py-4 flex justify-between items-center shadow-sm">
        <div className="flex items-center gap-3">
          <div className="bg-green-100 p-2 rounded-lg">
            <CurrencyDollarIcon className="h-6 w-6 text-green-600" />
          </div>
          <div>
            <h1 className="text-lg font-bold text-gray-800 leading-none">
              Agri-Tracker
            </h1>
            <p className="text-xs text-gray-500 font-medium mt-1">
              Welcome,{" "}
              <span className="text-green-600 uppercase">
                {user?.email?.split("@")[0]}
              </span>
            </p>
          </div>
        </div>

        <button
          onClick={() => signOut(auth)}
          className="flex items-center gap-2 text-sm text-red-500 font-bold hover:bg-red-50 px-3 py-2 rounded-lg transition"
        >
          <ArrowRightOnRectangleIcon className="h-5 w-5" />
          Logout
        </button>
      </header>

      <main className="p-6 max-w-6xl mx-auto w-full flex-1">
        {!selectedCropId ? (
          /* --- CROP SELECTION --- */
          <div className="animate-in fade-in duration-500">
            <div className="flex justify-between items-center mb-8">
              <div>
                <h2 className="text-2xl font-black text-gray-800">Crops</h2>
                <p className="text-gray-500">
                  Select a campaign to manage expenses
                </p>
              </div>
              <button
                onClick={() => setShowCropModal(true)}
                className="bg-blue-600 text-white px-5 py-2.5 rounded-xl flex items-center gap-2 hover:bg-blue-700 shadow-md transition"
              >
                <PlusIcon className="h-5 w-5" /> New Crop
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {crops.map((crop) => (
                <div
                  key={crop.id}
                  onClick={() => setSelectedCropId(crop.id)}
                  className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:border-blue-400 hover:shadow-xl cursor-pointer transition-all group relative overflow-hidden"
                >
                  <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition">
                    <TagIcon className="h-16 w-16" />
                  </div>
                  <h3 className="text-xl font-bold text-gray-800 z-10 relative">
                    {crop.name}
                  </h3>
                  <p className="text-gray-400 text-sm mt-1">
                    View Detailed Ledger &rarr;
                  </p>
                </div>
              ))}
            </div>
          </div>
        ) : (
          /* --- EXPENSE DASHBOARD --- */
          <div className="animate-in slide-in-from-right duration-300">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
              <button
                onClick={() => setSelectedCropId(null)}
                className="flex items-center gap-2 text-gray-500 hover:text-gray-800 transition font-bold"
              >
                <ArrowLeftIcon className="h-4 w-4" /> Back to Crops
              </button>

              <button
                onClick={exportToPDF}
                className="bg-gray-800 text-white px-4 py-2 rounded-xl flex items-center gap-2 hover:bg-black transition text-sm shadow-lg"
              >
                <ArrowDownTrayIcon className="h-4 w-4" /> Export PDF Report
              </button>
            </div>

            <div className="bg-white p-8 rounded-3xl shadow-sm border mb-8 flex flex-col md:flex-row justify-between items-center gap-6">
              <div>
                <h2 className="text-4xl font-black text-gray-900">
                  {activeCrop?.name}
                </h2>
                <p className="text-gray-400 font-medium">
                  Expense Management Dashboard
                </p>
              </div>
              <button
                onClick={() => setShowExpenseModal(true)}
                className="w-full md:w-auto bg-green-600 text-white px-8 py-4 rounded-2xl shadow-lg hover:bg-green-700 flex items-center justify-center gap-2 font-bold text-lg"
              >
                <PlusIcon className="h-6 w-6" /> Add New Expense
              </button>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
              <div className="bg-white p-6 rounded-2xl shadow-sm border-t-4 border-blue-500">
                <p className="text-xs font-black text-gray-400 uppercase tracking-widest">
                  Grand Total
                </p>
                <p className="text-3xl font-black text-gray-800 mt-1">
                  PKR {total.toLocaleString()}
                </p>
              </div>
              <div className="bg-white p-6 rounded-2xl shadow-sm border-t-4 border-purple-500">
                <p className="text-xs font-black text-gray-400 uppercase tracking-widest">
                  Dr Shahzad
                </p>
                <p className="text-3xl font-black text-purple-600 mt-1">
                  PKR {shahzadTotal.toLocaleString()}
                </p>
              </div>
              <div className="bg-white p-6 rounded-2xl shadow-sm border-t-4 border-green-500">
                <p className="text-xs font-black text-gray-400 uppercase tracking-widest">
                  Azhar
                </p>
                <p className="text-3xl font-black text-green-600 mt-1">
                  PKR {azharTotal.toLocaleString()}
                </p>
              </div>
            </div>

            {/* Tables */}
            <div className="grid lg:grid-cols-2 gap-8">
              {["Dr Shahzad", "Azhar"].map((partner) => (
                <div
                  key={partner}
                  className="bg-white rounded-2xl shadow-sm border overflow-hidden"
                >
                  <div
                    className={`p-4 border-b flex items-center gap-2 font-bold ${partner === "Azhar" ? "text-green-700 bg-green-50" : "text-purple-700 bg-purple-50"}`}
                  >
                    <UserCircleIcon className="h-5 w-5" />
                    {partner}'s Expenses
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-left">
                      <thead className="bg-gray-50 text-xs uppercase text-gray-400 font-bold">
                        <tr>
                          <th className="px-4 py-3">Description</th>
                          <th className="px-4 py-3 text-right">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y">
                        {filteredExpenses
                          .filter((e) => e.addedBy === partner)
                          .map((e) => (
                            <tr
                              key={e.id}
                              className="hover:bg-gray-50 transition"
                            >
                              <td className="px-4 py-3">
                                <p className="text-sm font-medium text-gray-800">
                                  {e.description}
                                </p>
                                <p className="text-[10px] text-gray-400">
                                  {new Date(e.date).toLocaleDateString()}
                                </p>
                              </td>
                              <td className="px-4 py-3 text-right font-bold text-gray-700 text-sm">
                                {e.amount.toLocaleString()}
                              </td>
                            </tr>
                          ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Create Crop Modal */}
        {showCropModal && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-white p-8 rounded-3xl shadow-2xl w-full max-w-sm">
              <h3 className="text-2xl font-black mb-2 text-gray-800">
                New Campaign
              </h3>
              <p className="text-sm text-gray-500 mb-6">
                Enter a name like "Wheat 2026"
              </p>
              <input
                className="w-full border-2 border-gray-100 focus:border-blue-500 outline-none p-4 rounded-xl mb-6 transition"
                placeholder="Crop Name"
                value={newCropName}
                onChange={(e) => setNewCropName(e.target.value)}
              />
              <div className="flex gap-3">
                <button
                  onClick={() => setShowCropModal(false)}
                  className="flex-1 py-3 text-gray-400 font-bold"
                >
                  Cancel
                </button>
                <button
                  onClick={handleAddCrop}
                  className="flex-1 py-3 bg-blue-600 text-white rounded-xl font-bold shadow-lg"
                >
                  Create
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Add Expense Modal */}
        {showExpenseModal && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-white p-8 rounded-3xl shadow-2xl w-full max-w-md">
              <h3 className="text-2xl font-black mb-1">Add Expense</h3>
              <p className="text-green-600 font-bold text-sm mb-6 uppercase tracking-wider">
                {activeCrop?.name}
              </p>

              <label className="block text-xs font-bold text-gray-400 mb-1 uppercase">
                Amount (PKR)
              </label>
              <input
                type="number"
                placeholder="0.00"
                className="w-full border-2 border-gray-100 focus:border-green-500 outline-none p-4 rounded-xl mb-4 text-xl font-bold"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
              />

              <label className="block text-xs font-bold text-gray-400 mb-1 uppercase">
                Description
              </label>
              <input
                type="text"
                placeholder="e.g. Fertilizer, Tube Well"
                className="w-full border-2 border-gray-100 focus:border-green-500 outline-none p-4 rounded-xl mb-8"
                value={desc}
                onChange={(e) => setDesc(e.target.value)}
              />

              <div className="flex gap-3">
                <button
                  onClick={() => setShowExpenseModal(false)}
                  className="flex-1 py-4 text-gray-400 font-bold"
                >
                  Cancel
                </button>
                <button
                  onClick={handleAddExpense}
                  className="flex-1 py-4 bg-green-600 text-white rounded-2xl font-bold text-lg shadow-xl hover:bg-green-700 transition"
                >
                  Save Record
                </button>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
